# Generated by Django 3.0.3 on 2020-02-18 18:17

from django.db import migrations

def seed(apps, schema_editor):
    Sender = apps.get_model('pobox_zero', 'Sender')
    Postcard = apps.get_model('pobox_zero', 'Postcard')
    anonymous = Sender(name='anonymous')
    aldo = Sender(name='Aldo')
    afriend = Sender(name='a friend')
    anonymous.save()
    aldo.save()
    afriend.save()

    Postcard(sender=anonymous, image_url='https://images.unsplash.com/photo-1579762593217-46655e4e7efc?ixlib=rb-1.2.1&auto=format&fit=crop&w=2180&q=80', heading='first off...', message='welcome to the rest of your life.').save()
    Postcard(sender=aldo, image_url='https://images.unsplash.com/photo-1579762593217-46655e4e7efc?ixlib=rb-1.2.1&auto=format&fit=crop&w=2180&q=80', heading='first off...', message='welcome to the rest of your life.').save()
    Postcard(sender=afriend, image_url='https://images.unsplash.com/photo-1579762593217-46655e4e7efc?ixlib=rb-1.2.1&auto=format&fit=crop&w=2180&q=80', heading='first off...', message='welcome to the rest of your life.').save()
    Postcard(sender=anonymous, image_url='https://images.unsplash.com/photo-1579762593217-46655e4e7efc?ixlib=rb-1.2.1&auto=format&fit=crop&w=2180&q=80', heading='first off...', message='welcome to the rest of your life.').save()
    Postcard(sender=aldo, image_url='https://images.unsplash.com/photo-1579762593217-46655e4e7efc?ixlib=rb-1.2.1&auto=format&fit=crop&w=2180&q=80', heading='first off...', message='welcome to the rest of your life.').save()
    Postcard(sender=anonymous, image_url='https://images.unsplash.com/photo-1579762593217-46655e4e7efc?ixlib=rb-1.2.1&auto=format&fit=crop&w=2180&q=80', heading='first off...', message='welcome to the rest of your life.').save()



def fallow(apps, schema_editor):
    Sender = apps.get_model('pobox_zero', 'Sender')
    Postcard = apps.get_model('pobox_zero', 'Postcard')
    Sender.objects.all().delete()
    Postcard.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('pobox_zero', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed, fallow)
    ]
