# Generated by Django 3.0.3 on 2020-02-21 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pobox_zero', '0003_auto_20200218_2105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcard',
            name='sender',
        ),
    ]
