# Generated by Django 3.0.3 on 2020-02-24 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pobox_zero', '0006_postcard_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcard',
            name='favorite',
        ),
    ]
