# Generated by Django 3.0.3 on 2020-02-24 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pobox_zero', '0008_postcard_favorited_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postcard',
            old_name='user',
            new_name='author',
        ),
    ]
