# Generated by Django 3.0.3 on 2020-02-25 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pobox_zero', '0011_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
