# Generated by Django 3.0.3 on 2020-03-19 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pobox_zero', '0013_auto_20200225_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcard',
            name='image',
            field=models.ImageField(default='default.png', upload_to='images'),
        ),
    ]
