# Generated by Django 3.0.3 on 2020-03-19 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pobox_zero', '0014_auto_20200319_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcard',
            name='image',
            field=models.ImageField(default='carousel-default.png', upload_to='images'),
        ),
    ]
